# Generated by Django 3.1.3 on 2023-05-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20230524_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='modify_times',
            field=models.IntegerField(default=0),
        ),
    ]
